## Tensorflow examples

1. Hello world
2. Basic tensor operations


### 1. Hello world
A very simple "hello world" using TensorFlow v2 tensors.

* Author: [Aymeric Damien](@Snapchat)
* Project: [https://github.com/aymericdamien/TensorFlow-Examples/](https://github.com/aymericdamien/TensorFlow-Examples/)

In [33]:
import tensorflow as tf

# Create a Tensor 
msg = tf.constant("hello world")
print(msg)

tf.Tensor(b'hello world', shape=(), dtype=string)


In [34]:
# To access a Tensor value, call numpy().
print(msg.numpy())

b'hello world'


### 2. Basic Tensor Operations
Basic tensor operations using TensorFlow v2.

* Author: [Aymeric Damien](@Snapchat)
* Project: [https://github.com/aymericdamien/TensorFlow-Examples/](https://github.com/aymericdamien/TensorFlow-Examples/)

In [35]:
from __future__ import print_function
import tensorflow as tf

In [37]:
# Defien tensor flow constants
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(5)
# Various tensor operations.
# Note: Tensors also support python operators (+, *, ...)
add = tf.add(a, b)
sub = tf.subtract(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a, b)
# Access tensors value.
print("add =", add.numpy())
print("sub =", sub.numpy())
print("mul =", mul.numpy())
print("div =", div.numpy())

add = 5
sub = -1
mul = 6
div = 0.6666666666666666


In [38]:
# Some more operations.
mean = tf.reduce_mean([a, b, c])
sum = tf.reduce_sum([a, b, c])

# Access tensors value.
print("mean =", mean.numpy())
print("sum =", sum.numpy())

mean = 3
sum = 10


In [43]:
# Matrix multiplications.
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[5., 6.], [7., 8.]])

product = tf.matmul(matrix1, matrix2)

tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)


In [40]:
product

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[19., 22.],
       [43., 50.]], dtype=float32)>

In [42]:
# Convert Tensor to Numpy.
product.numpy()

array([[19., 22.],
       [43., 50.]], dtype=float32)